spring:
  application:
    name: Venus

---
spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    show-sql: false

venus:
  message: Hello, world!

